name: Create Modpack Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release assets directory
        run: |
          mkdir release_assets
          cp -r overrides release_assets/
          cp manifest.json release_assets/
          cp modlist.html release_assets/
          cp modpack.png release_assets/

      - name: Zip release assets
        run: |
          cd release_assets
          zip -r ../BasedVanilla-${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: BasedVanilla-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 